# **Diagonal**

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)
print (matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Diagonal no cuadrada

In [3]:
print(matriz[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [6]:
v1 = np.array([1,1,1,1])
print(V1)
print(A.dot(v1.T))

[1 1 1 1]
[2 3 4 5]


# **Inversa**

In [7]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Tambien se puede calcular por:

In [8]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


# **Simetrica**

In [10]:
simetrica = np.array([[1,2,3],
                     [2,-1,7],
                     [3,7,11]])
print(simetrica == simetrica.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
