In [20]:
import numpy as np

In [21]:
escalar = 5.679
vector = np.array([2,3])
matriz =  np.array([[1,2], [3,4], [5,6]])

In [22]:
A = matriz * vector

#.dot producto interno

In [23]:
B = matriz.dot(vector)

In [24]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [25]:
print(B)

[ 8 18 28]


In [27]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]
