In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2], [7,8]])
tensor = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
    
])

In [3]:
print (escalar)

5.679


In [8]:
#.shape para que cada objeto nos devuelva sus dimensiones, el escalar no tendria

In [5]:
vector.shape

(3,)

In [6]:
matriz.shape

(2, 2)

In [7]:
tensor.shape

(3, 3, 3)

In [9]:
#.len, nos devuelve menos informacion, solo es su tamaño

In [10]:
len(vector)
len(matriz)
len(tensor)

3

In [12]:
len(matriz)

2

In [13]:
#size cantidad de elementos 

In [14]:
print(matriz.size)

4


# Transposition

In [15]:
tensor = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
    
])

In [18]:
vector_t = vector.T
print (vector_t)

[1 2 3]


In [19]:
matriz_t = matriz.T
print (matriz_t)

[[1 7]
 [2 8]]


In [20]:
tensor_t = tensor.T
print (tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]


In [21]:
print (tensor.shape)
print (tensor_t.shape)

(3, 3, 3)
(3, 3, 3)


# Suma

In [22]:
#Si tienen la mismas dimensiones entre matrices, se pueden sumar

In [26]:
A = matriz
B = matriz_t
suma = A+B
print(suma)

[[ 2  9]
 [ 9 16]]


In [29]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print (C)

[[7 7]
 [7 7]
 [7 7]]


In [30]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [12.679 13.679]]
